[[Faiss]]
arch = "aarch64"
git-tree-sha1 = "ae767a50e6c92a29d2936b1f95df554008a1bdda"
os = "macos"

    [[Faiss.download]]
    sha256 = "f84c95dcb2e2b890c5aab0aa6b5e041bb2215c79da6da7720e2e0f9114ee55e2"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.aarch64-apple-darwin.tar.gz"
[[Faiss]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33641e4fe11e863c75f98b8ff6e5037067102121"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "a26e5bce015181ed9fd08fa67303309afe0eede0715be057b73094ea52f2b284"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Faiss]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "945ff281d8185cb642f0f09c408b63229e461ca4"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "0713be8d169cc95d24a8b8b33bfae52be4223c491f13dc1fa3f1577af696eaa0"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Faiss]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bde4200bdd26c6139915741b5bfb99334f791f4d"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "ecc87b6a51330adae93ce584de010fe11808d0f81c296e52782479b9499eed5d"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.aarch64-linux-musl-cxx03.tar.gz"
[[Faiss]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "458efcacf31b32a07003a15196d41788c034be87"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "a18b04e6945ee1b3a13cc0d9f6a815807dc4fd8866838a5e64e9e729f89a85a4"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[Faiss]]
arch = "aarch64"
git-tree-sha1 = "9127e5ff0e699d342c827f722a553edc56eaae35"
os = "freebsd"

    [[Faiss.download]]
    sha256 = "8a67f19f8f5f354465ce016ee1a55d9d86d12918cb8b7a1adf9aaac76fa371a6"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.aarch64-unknown-freebsd.tar.gz"
[[Faiss]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f9c9a69348d84d69df0ac8aa6cb1d2395b149da3"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "084f98fa4e8bc6140b03f93d714c88fda4eff144a18742973c463ea2d354e653"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Faiss]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3738ff8fc20fedede517280a8a4889e5ab73e6dc"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "a7ff136c69d4f775bdd76beb5735e7dbd25cb8bc03eb31739e90ea19418927ac"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Faiss]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7be61ea6a9b80b2c603a8b2f307834358fc7b94d"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "ba249a6690f2f968483d0d6d3f3dd54ccd99d191e97e007b56f6c0ed750e4eb5"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Faiss]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be909375095f55a20124f124c11a1066523ac4b9"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "28d6435f6bc3c48b7607dfe96fe4939016a1dd07610c7d6beb21ff703aa05074"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Faiss]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "93e11184f86c0e873662a9e93fcb59d14640a3ae"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "ad953509e90797ab1f4c6d5faad508f9c92855455482b0f6c5d724be961a7c74"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Faiss]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a01299b80b6b49022536113e3538ed8da41a6e23"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "bec76103bca45f1cf38c55af1185c7975097d43d860ccbe0231b03a77e9b1d5e"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Faiss]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46100fcc0d25efe852f8dfb52567aca9a6957d16"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "58903ad1cd0b8e2652da472bb468d434a0c51ac7413acc510f623dc027d96da5"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Faiss]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97e51ec280f136683d5c0d68b124c071ec63e60c"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "1fd4d3a3217b144cf85da362a487c9a6b10c2d0d35cbbcb907431138b6fe2e99"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Faiss]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "606bb605d073fc41e298b1a7ef8f1e9581423c99"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "5feca060f3f8adbddf6ae9fefaa878272ccb1911354d2e673dff920e56a8110e"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.i686-linux-gnu-cxx03.tar.gz"
[[Faiss]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db6f136e49e5e14a83dcaa6330aea1f4b74a9808"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "200d734c8b0b7629c26191d17d654f30a069d3459c23099167c63172f8298e2c"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.i686-linux-gnu-cxx11.tar.gz"
[[Faiss]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88f39f9fefa701b2fa33f4cfedb864d4c57e5370"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "3d9182a997942c0b7051ee70561ed6eb1c1708fd8b22a71a4590d99ed57f3f5d"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.i686-linux-musl-cxx03.tar.gz"
[[Faiss]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fbd648d8c7f0a38a263061a2eab1b7f9e6ba58d9"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "5b1d21654bb4ec4c03cfa0c0203b466cc987278bb6bd2e85cb67b549078e99ed"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.i686-linux-musl-cxx11.tar.gz"
[[Faiss]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e665400727d67a64477b3c09640c2e8245aa9ee4"
os = "windows"

    [[Faiss.download]]
    sha256 = "05d7d607aeb7f8aef83a7eb78ac2c554f68379de6404af32b65c1928a2e3f392"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.i686-w64-mingw32-cxx03.tar.gz"
[[Faiss]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e7d9b684c434b4baf6a4550c582807df431f8a2b"
os = "windows"

    [[Faiss.download]]
    sha256 = "47db2eceff192bb818b2b1e391866a7a6fcb02f0349832514937aeee0cbc32e5"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.i686-w64-mingw32-cxx11.tar.gz"
[[Faiss]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5b27692ae102c4a7303fd4f5c46e8d7c008c594"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "127f0b99659e1cc4ffe800cc9cbb4a198c07aa16b082e6b86edc1ec72d890f27"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Faiss]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce9a4c5bc1b53d5784ff9639cbfc8a39ad0b6398"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "c847df35bda4b7450814f7b5ffddd01cb816513faf4e06d595637de87a9ebaee"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Faiss]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55a862cd174a6136ae84d13f6fa9e3a6d1b24828"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "5769d8e494a4c96ddf4f8ec147d032cf8ebf4472ca59bef0836c16bd164842f9"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.riscv64-linux-gnu-cxx03.tar.gz"
[[Faiss]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9694dca8fb3d06a846876a8a06188b8dc4c241be"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "72043afae49e1a19f434143f66baa3ce02f88ecb73ccb5a9e0f613eb61745a4f"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.riscv64-linux-gnu-cxx11.tar.gz"
[[Faiss]]
arch = "x86_64"
git-tree-sha1 = "bc3c06877423dd2fa7fb2fd394e0b394d420de23"
os = "macos"

    [[Faiss.download]]
    sha256 = "3eaccfd3c5b3333fba4d22c96102923d12578856f6ee8662555f0dcaa647973c"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-apple-darwin.tar.gz"
[[Faiss]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d1de918190d14e464c974033f376082590ee317d"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "bb7b649e33233b131f489434fdd2f99e2e8722ab1e2f755374ca2c632ae69253"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Faiss]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b67733a673649a993519525c5ed659b9fac5d6ff"
libc = "glibc"
os = "linux"

    [[Faiss.download]]
    sha256 = "eb76f8f9eb26855320064b31fd21a6b3ab8c253b74f60bf2ab61d1e2f678742f"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Faiss]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e67bed3e98e122e39d962190090d0ef4478d5a82"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "fa268995b8134dff12a6b6ca6ea9c62859ea35344651aa32c3793500f8e0016b"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-linux-musl-cxx03.tar.gz"
[[Faiss]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f63f99105ceaf71c37802963d8c56c13ccee94a6"
libc = "musl"
os = "linux"

    [[Faiss.download]]
    sha256 = "4a27d254bd1cd398be3df070eb4ec5fef3527b95e783a26e97f8518cd944a4d7"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-linux-musl-cxx11.tar.gz"
[[Faiss]]
arch = "x86_64"
git-tree-sha1 = "e56e9be66dc2199b98438c1ff57a2dc417d63a97"
os = "freebsd"

    [[Faiss.download]]
    sha256 = "303d757eec9b098b506bf877029cd424bdb2d69310f49a0039a0fd5593c948ce"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-unknown-freebsd.tar.gz"
[[Faiss]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4392de28bf54edaa35f4107e74b990389146ef38"
os = "windows"

    [[Faiss.download]]
    sha256 = "ae102208102e723ff7c0189629e14fd63c4eb8773cf435f1a2e4c4ae1ca94a23"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Faiss]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ab2aae44a8a579b68094e7160a0fdaf6c1283961"
os = "windows"

    [[Faiss.download]]
    sha256 = "80bf11d15fbcd882e8c265724c45d467da3e19f016f014bebde40e687f3225dc"
    url = "https://github.com/JuliaBinaryWrappers/Faiss_jll.jl/releases/download/Faiss-v1.9.0+0/Faiss.v1.9.0.x86_64-w64-mingw32-cxx11.tar.gz"
